### ISSUE TITLE
Harvester refused connection (Docker installation)

### ISSUE THREAD

**Issue by lwuersch** [Esri/geoportal-server-catalog#305]
Hi all,
I installed Geoportal 2 following these instructions: https://github.com/Esri/geoportal-server-catalog/tree/master/docker#installation
Geoportal is running nicely and I can access it on localhost:8082. However, when attempting to harvest data from http://hydro10.sdsc.edu/metadata/example/, I am getting a Connection refused error. I would highly appreciate support in this regard (i could add the full one if that would be helpful).

Below, find the configuration used for the input/output brokers, the result window displayed in the harvester and also a part of the stacktrace:
![inputBrokerConfig](https://user-images.githubusercontent.com/22364707/66144092-7fd05f80-e608-11e9-88fe-30822c458ea8.png)
![outputBrokerConfig](https://user-images.githubusercontent.com/22364707/66144101-83fc7d00-e608-11e9-82f2-86e56645a7eb.png)
![Result_displayInHarvester](https://user-images.githubusercontent.com/22364707/66144118-8b238b00-e608-11e9-976f-770a8f66f1ea.png)

26-Sep-2019 09:50:04.756 SEVERE [HARVESTING] com.esri.geoportal.harvester.support.ErrorLogger.logError Error processing task: PROCESS:: status: working, title: NAME: , PROCESSOR: DEFAULT[], SOURCE: WAF[waf-host-url=http://hydro10.sdsc.edu/metadata/example/, waf-pattern=, cred-username=, cred-password=*****], DESTINATIONS: [GPT[gpt-host-url=http://localhost:8082/geoportal, cred-username=gptadmin, cred-password=*****, gpt-index=, gpt-cleanup=false, gpt-accept-xml=true, gpt-accept-json=true, gpt-translate-pdf=true]], INCREMENTAL: false, IGNOREROBOTSTXT: true | Error publishing data: id: http://hydro10.sdsc.edu/metadata/example/dublincore/dc_with_references_noaa.xml, modified: Thu May 24 19:03:05 UTC 2018, source URI: http://hydro10.sdsc.edu/metadata/example/dublincore/dc_with_references_noaa.xml, broker URI: WAF:http://hydro10.sdsc.edu/metadata/example/
        com.esri.geoportal.harvester.api.ex.DataOutputException: Error publishing data: id: http://hydro10.sdsc.edu/metadata/example/dublincore/dc_with_references_noaa.xml, modified: Thu May 24 19:03:05 UTC 2018, source URI: http://hydro10.sdsc.edu/metadata/example/dublincore/dc_with_references_noaa.xml, broker URI: WAF:http://hydro10.sdsc.edu/metadata/example/
                at com.esri.geoportal.harvester.gpt.GptBroker.publish(GptBroker.java:213)
                at com.esri.geoportal.harvester.api.base.BrokerLinkActionAdaptor.push(BrokerLinkActionAdaptor.java:64)
                at com.esri.geoportal.harvester.api.base.SimpleLink.push(SimpleLink.java:71)
                at com.esri.geoportal.harvester.engine.defaults.DefaultProcessor$DefaultProcess.lambda$null$0(DefaultProcessor.java:158)
                at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
                at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
                at com.esri.geoportal.harvester.engine.defaults.DefaultProcessor$DefaultProcess.lambda$new$1(DefaultProcessor.java:156)
                at java.lang.Thread.run(Thread.java:748)
        Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8082 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
                at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)

**Comment by valentinedwv** [comment]
I think the publish needs to be 8080. That is the internal dock port. This is exposed as 8082 to the outside world.

**Comment by lwuersch** [comment]
thank you, so I changed the output brokers local host port to 8080, that worked
